#!/usr/bin/env bash

## Description: Export neo4j database in Cypher format
## Usage: neo4j-export
## Example: ddev neo4j-export

bin/cypher-shell << 'CYPHER'
CALL apoc.export.cypher.all("all.cypher", {
    format: "cypher-shell",
    useOptimizations: {type: "UNWIND_BATCH_PARAMS", unwindBatchSize: 500}
})
YIELD file, batches, source, format, nodes, relationships, properties, time, rows, batchSize
RETURN file, batches, source, format, nodes, relationships, properties, time, rows, batchSize;
CYPHER
