#!/usr/bin/env bash

## Description: Export neo4j database in Cypher format
## Usage: neo4j-export
## Example: ddev neo4j-export

# Optional first argument for filename, default value should be all.cypher
filename="all.cypher"
if [[ -n "$1" ]]; then
  filename="$1"
fi

bin/cypher-shell << CYPHER
CALL apoc.export.cypher.all("${filename}", {
    format: "cypher-shell",
    writeNodeProperties: true,
    useOptimizations: {type: "UNWIND_BATCH_PARAMS", unwindBatchSize: 500}
})
YIELD file, batches, source, format, nodes, relationships, properties, time, rows, batchSize
RETURN file, batches, source, format, nodes, relationships, properties, time, rows, batchSize;
CYPHER

chmod 777 -R /var/lib/neo4j/import
sed -i 's/\xE2\x80\xA8//g' /var/lib/neo4j/import/${filename}

