services:
  neo4j:
    container_name: "ddev-${DDEV_SITENAME}-neo4j"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    image: neo4j
    expose:
      - "7474"
      - "7687"
    volumes:
#      - ${DDEV_APPROOT}/neo4j-database:/data
      - ${DDEV_APPROOT}/neo4j-exports:/var/lib/neo4j/import
      - ".:/mnt/ddev_config:ro"
    environment:
      - NEO4J_AUTH=none
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=7474:7474
      - HTTPS_EXPOSE=7687:7687
      - NEO4J_db_tx__log_rotation_size=128K
      - NEO4J_db_tx__log_rotation_retention__policy=keep_none
      - NEO4J_db_checkpoint_interval_time=1M
      - NEO4J_db_recovery_fail__on__missing__files=false
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
